language: python
python:
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
script:
    - make test
after_success:
    - codecov
