language: python
python:
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
script:
    - pytest
after_success:
    - codecov
